exclude: '\.svg$|ap_types/|_version.py'

repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.14.2
  hooks:
    - id: ruff-check
      types_or: [ python, pyi ]
      args: [ --fix ]
    - id: ruff-format
      types_or: [ python, pyi ]

- repo: https://github.com/tox-dev/pyproject-fmt
  rev: v2.11.0
  hooks:
    - id: pyproject-fmt

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-yaml
  - id: check-toml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: requirements-txt-fixer
  - id: trailing-whitespace

- repo: https://github.com/asottile/pyupgrade
  rev: v3.21.0
  hooks:
  - id: pyupgrade
    args: ["--py310-plus"]

- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v21.1.2
  hooks:
  - id: clang-format
    types_or: [c++, c, cuda]
